### ISSUE TITLE
ZSH spawned processes are re-prioritized with nice 

### ISSUE THREAD

**Issue by g4mma4** [0xC0FFEEEE/haxtools#3]
Zsh quietly sets nice on processes spawned by zsh on remote machines. Would you consider adding `setopt NO_BG_NICE` as a default to make this magical behavior explicit?             

http://zsh.sourceforge.net/Guide/zshguide02.html

**Comment by breakfixrepeat** [comment]
Absolutely, I will look in to this and push the change in the next day or two.

In the meantime you can add this directly to your `.haxtools/home/.zshrc` file.

**Comment by breakfixrepeat** [comment]
I have updated .zshrc and pushed the change.

Thanks for the suggestion, I wasn't aware of this default behaviour!

**Comment by g4mma4** [comment]
Thank you!
